server {
	listen 443 ssl;
	server_name test.example.ir;
	server_tokens off;

	ssl_certificate /etc/letsencrypt/live/test.example.ir/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/test.example.ir/privkey.pem;

	location = /api/v1/users/test {
		proxy_redirect off;
		proxy_pass http://127.0.0.1:1410;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
		proxy_set_header Host $http_host;
	}
}
