bind 0.0.0.0
port 6379
dir /data
replicaof redis-master.redis-ha_redis-net 6379
appendonly yes
protected-mode no
replica-announce-ip redis-replica1.redis-ha_redis-net
replica-announce-port 6379
requirepass 5d580bc458a203f8e7eb
masterauth 5d580bc458a203f8e7eb
