bind 0.0.0.0
port 6379
replicaof 192.168.59.20 6379
dir /data
appendonly yes
appendfsync everysec
save ""
protected-mode no
replica-announce-ip 192.168.59.21
replica-announce-port 6379
aclfile /usr/local/etc/redis/users.acl
masteruser replica
masterauth c24c2ed886c65bdefff7
