server {
    listen 80;
    server_name server_name;
    more_set_headers "Server: Microsoft-IIS/10.0";

    if ($http_x_forwarded_proto = "http") {
        return 301 https://$host$request_uri;
    }

    if ($scheme = "http") {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name server_name;
    server_tokens off;
    more_set_headers "Server: Microsoft-IIS/10.0";
    ssl_certificate /opt/cert/fullchain.pem;
    ssl_certificate_key /opt/cert/privkey.pem;
    client_max_body_size 300M;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        proxy_pass http://127.0.0.1:8080;
        autoindex off;
        auth_basic "Restricted Area";
        auth_basic_user_file /etc/nginx/.htpasswd;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
        proxy_set_header X-Scheme $http_x_forwarded_proto;
    }

    location /downloads/ {
        proxy_pass http://127.0.0.1:8081/;
        autoindex on;
        auth_basic "Restricted Area";
        auth_basic_user_file /etc/nginx/.htpasswd;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}