bind 0.0.0.0
port 26379
protected-mode no
sentinel resolve-hostnames yes
sentinel announce-hostnames yes
sentinel announce-port 26379
sentinel monitor mymaster 192.168.59.22 6379 2
sentinel down-after-milliseconds mymaster 5000
sentinel failover-timeout mymaster 5000
sentinel parallel-syncs mymaster 1
dir /data
sentinel auth-user mymaster sentinel
sentinel auth-pass mymaster 99540d17f0d2f0887ca2
sentinel sentinel-user senuser
sentinel sentinel-pass 382828e2bfb12c5aac5a1a20
aclfile /usr/local/etc/redis/users.acl

