server {
        listen 80;
        server_name localhost;
        server_tokens off;
        root /usr/share/nginx/html;
        index index.html;

        location / {
            autoindex on;
            try_files $uri $uri/ =404;
        }

        location ~* \.(txt|json|yaml|yml|pdf|jpg})$ {
            add_header Content-Disposition "attachment";
        }
}
